In [ ]:
from proture.utils import explode

In [1]:
import pandas as pd 

import warnings
warnings.filterwarnings("ignore")

pd.set_option('display.max_columns', 100)

In [46]:
from copy import deepcopy
def explode(df:pd.DataFrame, column:str, sep:str = ","):
    tmp = deepcopy(df)  # shallow copy 

    tmp[column] = tmp[column].apply(lambda x: x.split(sep))
    return tmp.explode(column)

In [57]:
# SIFTS_mapping_dir = "/p300s/wangmx_group/xutingfeng/statistic/proture/data/SIFTS/homo_sapians_SIFITS_UniProt.csv"

SIFTS_mapping_dir = "/p300s/wangmx_group/xutingfeng/statistic/proture/data/SIFTS/homo_sapians_UniProt.tsv"

In [58]:
SIFTS_mapping_df = pd.read_csv(SIFTS_mapping_dir, sep="\t", index_col=False)

In [59]:
SIFTS_mapping_df[SIFTS_mapping_df["Gene Names"].isna()]

,From,Entry,Entry Name,Protein names,Gene Names,Organism,Length
86,O00370,O00370,LORF2_HUMAN,LINE-1 retrotransposable element ORF2 protein ...,NaN,Homo sapiens (Human),1275
1276,P0DOX5,P0DOX5,IGG1_HUMAN,Immunoglobulin gamma-1 heavy chain (Immunoglob...,NaN,Homo sapiens (Human),449
1277,P0DOX7,P0DOX7,IGK_HUMAN,Immunoglobulin kappa light chain (Immunoglobul...,NaN,Homo sapiens (Human),214
1278,P0DOX8,P0DOX8,IGL1_HUMAN,Immunoglobulin lambda-1 light chain (Immunoglo...,NaN,Homo sapiens (Human),216

In [60]:
SIFTS_mapping_df[SIFTS_mapping_df["Entry"] == "P68431"]

,From,Entry,Entry Name,Protein names,Gene Names,Organism,Length
2816,P68431,P68431,H31_HUMAN,Histone H3.1 (Histone H3/a) (Histone H3/b) (Hi...,H3C1 H3FA HIST1H3A; H3C2 H3FL HIST1H3B; H3C3 H...,Homo sapiens (Human),136

In [80]:
SIFTS_mapping_df[SIFTS_mapping_df["Gene Names"] == "SIRPB1"]

,From,Entry,Entry Name,Protein names,Gene Names,Organism,Length
68,O00241,O00241,SIRB1_HUMAN,Signal-regulatory protein beta-1 (SIRP-beta-1)...,SIRPB1,Homo sapiens (Human),398
3797,Q5TFQ8,Q5TFQ8,SIRBL_HUMAN,Signal-regulatory protein beta-1 isoform 3 (SI...,SIRPB1,Homo sapiens (Human),398

In [61]:
add_df = SIFTS_mapping_df[SIFTS_mapping_df["Gene Names"].isna()] 
add_df["Gene Names"] = add_df["Entry Name"].apply(lambda x: x.split("_")[0])

tmp_df = pd.concat([SIFTS_mapping_df, add_df])

SIFTS_mapping_df_full = tmp_df.dropna(subset=["Gene Names"])
SIFTS_mapping_df_full

,From,Entry,Entry Name,Protein names,Gene Names,Organism,Length
0,A0A075B6T6,A0A075B6T6,TVAL2_HUMAN,T cell receptor alpha variable 12-2,TRAV12-2,Homo sapiens (Human),113
1,A0A0B4J1U6,A0A0B4J1U6,TVB9_HUMAN,T cell receptor beta variable 9,TRBV9,Homo sapiens (Human),114
2,A0A0B4J268,A0A0B4J268,TVA4_HUMAN,T cell receptor alpha variable 4,TRAV4,Homo sapiens (Human),109
3,A0A0B4J2H0,A0A0B4J2H0,HV69D_HUMAN,Immunoglobulin heavy variable 1-69D,IGHV1-69D,Homo sapiens (Human),117
4,A0A0C4DH28,A0A0C4DH28,TRGV4_HUMAN,T cell receptor gamma variable 4,TRGV4 TCRGV4,Homo sapiens (Human),118
...,...,...,...,...,...,...,...
6405,W5XKT8,W5XKT8,SACA6_HUMAN,Sperm acrosome membrane-associated protein 6 (...,SPACA6 SPACA6P UNQ2487/PRO5774,Homo sapiens (Human),324
86,O00370,O00370,LORF2_HUMAN,LINE-1 retrotransposable element ORF2 protein ...,LORF2,Homo sapiens (Human),1275
1276,P0DOX5,P0DOX5,IGG1_HUMAN,Immunoglobulin gamma-1 heavy chain (Immunoglob...,IGG1,Homo sapiens (Human),449
1277,P0DOX7,P0DOX7,IGK_HUMAN,Immunoglobulin kappa light chain (Immunoglobul...,IGK,Homo sapiens (Human),214
1278,P0DOX8,P0DOX8,IGL1_HUMAN,Immunoglobulin lambda-1 light chain (Immunoglo...,IGL1,Homo sapiens (Human),216

In [40]:
SIFTS_mapping_df_full = explode(SIFTS_mapping_df_full, column="Gene Names", str = " ")  # 切分属于多个基因的Uniprot Accession

In [45]:
SIFTS_mapping_df_full

,From,Entry,Entry Name,Protein names,Gene Names,Organism,Length
0,A0A075B6T6,A0A075B6T6,TVAL2_HUMAN,T cell receptor alpha variable 12-2,TRAV12-2,Homo sapiens (Human),113
1,A0A0B4J1U6,A0A0B4J1U6,TVB9_HUMAN,T cell receptor beta variable 9,TRBV9,Homo sapiens (Human),114
2,A0A0B4J268,A0A0B4J268,TVA4_HUMAN,T cell receptor alpha variable 4,TRAV4,Homo sapiens (Human),109
3,A0A0B4J2H0,A0A0B4J2H0,HV69D_HUMAN,Immunoglobulin heavy variable 1-69D,IGHV1-69D,Homo sapiens (Human),117
4,A0A0C4DH28,A0A0C4DH28,TRGV4_HUMAN,T cell receptor gamma variable 4,TRGV4,Homo sapiens (Human),118
...,...,...,...,...,...,...,...
6405,W5XKT8,W5XKT8,SACA6_HUMAN,Sperm acrosome membrane-associated protein 6 (...,UNQ2487/PRO5774,Homo sapiens (Human),324
86,O00370,O00370,LORF2_HUMAN,LINE-1 retrotransposable element ORF2 protein ...,LORF2,Homo sapiens (Human),1275
1276,P0DOX5,P0DOX5,IGG1_HUMAN,Immunoglobulin gamma-1 heavy chain (Immunoglob...,IGG1,Homo sapiens (Human),449
1277,P0DOX7,P0DOX7,IGK_HUMAN,Immunoglobulin kappa light chain (Immunoglobul...,IGK,Homo sapiens (Human),214
1278,P0DOX8,P0DOX8,IGL1_HUMAN,Immunoglobulin lambda-1 light chain (Immunoglo...,IGL1,Homo sapiens (Human),216

In [50]:
explode(SIFTS_mapping_df_full, column = "Gene Names", sep = "/")["Gene Names"].to_csv("test.csv", index=False)

In [75]:
explode_SIFTS_mapping_df_full = explode(SIFTS_mapping_df_full, "Gene Names", sep=";")
explode_SIFTS_mapping_df_full

,From,Entry,Entry Name,Protein names,Gene Names,Organism,Length
0,A0A075B6T6,A0A075B6T6,TVAL2_HUMAN,T cell receptor alpha variable 12-2,TRAV12-2,Homo sapiens (Human),113
1,A0A0B4J1U6,A0A0B4J1U6,TVB9_HUMAN,T cell receptor beta variable 9,TRBV9,Homo sapiens (Human),114
2,A0A0B4J268,A0A0B4J268,TVA4_HUMAN,T cell receptor alpha variable 4,TRAV4,Homo sapiens (Human),109
3,A0A0B4J2H0,A0A0B4J2H0,HV69D_HUMAN,Immunoglobulin heavy variable 1-69D,IGHV1-69D,Homo sapiens (Human),117
4,A0A0C4DH28,A0A0C4DH28,TRGV4_HUMAN,T cell receptor gamma variable 4,TRGV4 TCRGV4,Homo sapiens (Human),118
...,...,...,...,...,...,...,...
6405,W5XKT8,W5XKT8,SACA6_HUMAN,Sperm acrosome membrane-associated protein 6 (...,SPACA6 SPACA6P UNQ2487/PRO5774,Homo sapiens (Human),324
86,O00370,O00370,LORF2_HUMAN,LINE-1 retrotransposable element ORF2 protein ...,LORF2,Homo sapiens (Human),1275
1276,P0DOX5,P0DOX5,IGG1_HUMAN,Immunoglobulin gamma-1 heavy chain (Immunoglob...,IGG1,Homo sapiens (Human),449
1277,P0DOX7,P0DOX7,IGK_HUMAN,Immunoglobulin kappa light chain (Immunoglobul...,IGK,Homo sapiens (Human),214
1278,P0DOX8,P0DOX8,IGL1_HUMAN,Immunoglobulin lambda-1 light chain (Immunoglo...,IGL1,Homo sapiens (Human),216

In [79]:
explode_SIFTS_mapping_df_full.groupby("Gene Names").apply(lambda x: pd.Series({"count": len(x)})).sort_values(by="count", ascending=False)

                      count
Gene Names
SIRPB1                    2
 C4B_2                    1
PLEKHB2 EVT2              1
PLP1 PLP                  1
PLOD3                     1
...                     ...
FUS TLS                   1
FURIN FUR PACE PCSK3      1
FUCA1 Nbla10230           1
FUBP1                     1
ZZZ3                      1

[6456 rows x 1 columns]